### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#100]
Issue:
- Device: Pixel 6
- OS: Android 12
- EP Version: Preview

How reproduce:
- Go to trackers tab
- Consult a tracker
- Go back to my apps tab
- Click on search bouton
- App crashed

**Comment by Jean-BaptisteC** [comment]
| Version | Detected |
| --- | --- |
| Android 5 | Yes |
| Android 7 | Yes |
| Android 8 | Yes |
| Android 12 | Yes |

**Comment by Jean-BaptisteC** [comment]
Other scenario:
- Consult report
- Go to trackers tab
- Go back to my apps tab
- Click on search bouton
- App crashed

The issue appears when you consult reports or trackers and switch tab.
I think this problem and #101 have a link

**Comment by Jean-BaptisteC** [comment]
* Stacktrace on Honor 8 - Android 8
```
04-09 14:29:32.839 15658 15658 E AndroidRuntime: FATAL EXCEPTION: main
04-09 14:29:32.839 15658 15658 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 15658
04-09 14:29:32.839 15658 15658 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at java.util.ArrayList.get(ArrayList.java:437)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.MainActivity$3.onQueryTextChange(MainActivity.java:266)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.widget.SearchView.onTextChanged(SearchView.java:1189)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.widget.SearchView$10.onTextChanged(SearchView.java:1727)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.widget.TextView.sendOnTextChanged(TextView.java:9589)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.widget.TextView.setText(TextView.java:5490)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.widget.TextView.setText(TextView.java:5343)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.widget.EditText.setText(EditText.java:113)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.widget.TextView.setText(TextView.java:5300)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.widget.SearchView.onActionViewExpanded(SearchView.java:1303)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2642)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1360)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:830)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:990)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.view.View.performClick(View.java:6291)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24931)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:808)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:101)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7523)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-09 14:29:32.839 15658 15658 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-09 14:29:32.848  1094  2066 W ActivityManager:   Force finishing activity org.eu.exodus_privacy.exodusprivacy/.MainActivity
```

**Comment by ItsIgnacioPortal** [comment]
Also verified on Android 9:

```
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: org.eu.exodus_privacy.exodusprivacy
PID: 8741
Flags: 0x30d83e44
Package: org.eu.exodus_privacy.exodusprivacy v12 (2.2.1)
Foreground: Yes
Build: motorola/pokerp_64/pokerp:9/PTBS29.401-58-2/58-2:user/release-keys

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.eu.exodus_privacy.exodusprivacy.MainActivity$c.a(Unknown Source:7)
	at androidx.appcompat.widget.SearchView.Y(Unknown Source:46)
	at androidx.appcompat.widget.SearchView$a.onTextChanged(Unknown Source:2)
	at android.widget.TextView.sendOnTextChanged(TextView.java:9771)
	at android.widget.TextView.setText(TextView.java:5750)
	at android.widget.TextView.setText(TextView.java:5588)
	at android.widget.EditText.setText(EditText.java:122)
	at android.widget.TextView.setText(TextView.java:5545)
	at androidx.appcompat.widget.SearchView.c(Unknown Source:28)
	at androidx.appcompat.widget.Toolbar$d.j(Unknown Source:125)
	at androidx.appcompat.view.menu.e.m(Unknown Source:45)
	at androidx.appcompat.view.menu.g.expandActionView(Unknown Source:22)
	at androidx.appcompat.view.menu.e.O(Unknown Source:38)
	at androidx.appcompat.view.menu.e.N(Unknown Source:1)
	at androidx.appcompat.widget.ActionMenuView.a(Unknown Source:3)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:6613)
	at android.view.View.performClickInternal(View.java:6586)
	at android.view.View.access$3100(View.java:780)
	at android.view.View$PerformClick.run(View.java:26100)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:235)
	at android.app.ActivityThread.main(ActivityThread.java:6760)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```
