### ISSUE TITLE
Crash on split screen

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#102]
Issue:
- Device: Pixel 6
- OS: Android 12
- EP Version: Preview

How reproduce:
- Open EP
- Leave app and go to menu open apps
- Enable split screen on EP
- EP is displayed on the half of the screen
- Consult a report
- App crashed

**Comment by Jean-BaptisteC** [comment]
Split screen is only available on Android 7 and up

**Comment by Jean-BaptisteC** [comment]
| Version | Detected |
| --- | --- |
| Android 5 | No |
| Android 7 | No |
| Android 8 | No |
| Android 12 | Yes |

**Comment by Jean-BaptisteC** [comment]
I think app crashed because when you enable split screen on app already open, app reload. 
I think we can fix issue if we fix https://github.com/Exodus-Privacy/exodus-android-app/issues/109 and add `android:resizeableActivity="true"` in [AndroidManifest.xml](app/src/main/AndroidManifest.xml)

Scenario  1:
- Open exodus app
- Use split screen
- App crashed

Scenario 2:
- Open another app
- Use split screen
- Open exodus app
- Split screen works in Exodus app

**Comment by Jean-BaptisteC** [comment]
Stacktrace on Honor 8 - Android 8
```
04-09 14:22:41.532  8670  8670 E AndroidRuntime: FATAL EXCEPTION: main
04-09 14:22:41.532  8670  8670 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 8670
04-09 14:22:41.532  8670  8670 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter$OnAppClickListener.onAppClick(org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationViewModel)' on a null object reference
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter.lambda$onBindViewHolder$0$org-eu-exodus_privacy-exodusprivacy-adapters-ApplicationListAdapter(ApplicationListAdapter.java:77)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.view.View.performClick(View.java:6291)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24931)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:808)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:101)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7523)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-09 14:22:41.532  8670  8670 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-09 14:22:41.535  1094  1567 W ActivityManager:   Force finishing activity org.eu.exodus_privacy.exodusprivacy/.MainActivity
```

**Comment by Jean-BaptisteC** [comment]
Duplicate of #109
