### ISSUE TITLE
Crash EP (menu share)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#106]
Issue:

- Device: Pixel 6
- OS: Android 12
- EP Version: Preview

How reproduce:

- Go to your app store, select an app is referenced on EP
- Use menu share on android, choose Exodus
- In the pop-up, select a tracker (tracker used by an another application from your phone)
- Select an application installed on your device
- Pop-up crashed

**Comment by Jean-BaptisteC** [comment]
| Version | Detected |
| --- | --- |
| Android 5 | Yes |
| Android 7 | Yes |
| Android 8 | Yes |
| Android 12 | Yes |

**Comment by Jean-BaptisteC** [comment]
* Stacktrace on Honor 8 - Android 8
```
04-09 14:38:12.781 17142 17142 E AndroidRuntime: FATAL EXCEPTION: main
04-09 14:38:12.781 17142 17142 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 17142
04-09 14:38:12.781 17142 17142 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter$OnAppClickListener.onAppClick(org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationViewModel)' on a null object reference
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter.lambda$onBindViewHolder$0$org-eu-exodus_privacy-exodusprivacy-adapters-ApplicationListAdapter(ApplicationListAdapter.java:77)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.view.View.performClick(View.java:6291)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24931)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:808)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:101)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7523)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
04-09 14:38:12.781 17142 17142 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
04-09 14:38:12.790  1094  5927 W ActivityManager:   Force finishing activity org.eu.exodus_privacy.exodusprivacy/.CheckAppActivity
```

**Comment by Jean-BaptisteC** [comment]
Duplicate of #109
