### ISSUE TITLE
Crash after actualization

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#181]
Android 12 - Pixel 6
Stacktrace:
```
06-11 22:15:18.779  1524  1655 I ActivityManager: Start proc 18872:org.eu.exodus_privacy.exodusprivacy/u0a386 for pre-top-activity {org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity}
06-11 22:15:18.832   500  2738 E SurfaceFlinger: Only WindowManager is allowed to use eEarlyWakeup[Start|End] flags
06-11 22:15:19.206 18872 18901 E SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=54, totalRows=55; query: SELECT * FROM exodusapplication
06-11 22:15:19.207 18872 18901 E AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
06-11 22:15:19.207 18872 18901 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 18872
06-11 22:15:19.207 18872 18901 E AndroidRuntime: java.lang.RuntimeException: Exception while computing database live data.
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:920)
06-11 22:15:19.207 18872 18901 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=54, totalRows=55
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1003)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:255)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:287)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.manager.database.app.ExodusApplicationDao_Impl$5.call(ExodusApplicationDao_Impl.java:370)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at org.eu.exodus_privacy.exodusprivacy.manager.database.app.ExodusApplicationDao_Impl$5.call(ExodusApplicationDao_Impl.java:352)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
06-11 22:15:19.207 18872 18901 E AndroidRuntime:        ... 3 more
```

**Comment by Jean-BaptisteC** [comment]
Report about this [app(Histoires de Metz)](https://reports.exodus-privacy.eu.org/fr/reports/263804/) generate crash and internal error

**Comment by Jean-BaptisteC** [comment]
https://github.com/Exodus-Privacy/exodus-android-app/blob/6a42b756753c97d5dce2da572eac2e083962bbcd/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/app/ExodusApplicationDao.kt#L21

**Comment by jfoucry** [comment]
Could adding a limit to the select fix the problem? See crash info `Row too big to fit into CursorWindow requiredPos=54`

**Comment by Jean-BaptisteC** [comment]
```
Exception java.lang.RuntimeException: Exception while computing database live data.
  at androidx.room.RoomTrackingLiveData$1.run (RoomTrackingLiveData.java:92)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)
Caused by android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=15, totalRows=16
  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow
  at android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:1009)
  at android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:838)
  at android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
  at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:153)
  at android.database.sqlite.SQLiteCursor.onMove (SQLiteCursor.java:123)
  at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:255)
  at android.database.AbstractCursor.moveToNext (AbstractCursor.java:287)
  at org.eu.exodus_privacy.exodusprivacy.manager.database.app.ExodusApplicationDao_Impl$5.call (ExodusApplicationDao_Impl.java:390)
  at org.eu.exodus_privacy.exodusprivacy.manager.database.app.ExodusApplicationDao_Impl$5.call (ExodusApplicationDao_Impl.java:371)
  at androidx.room.RoomTrackingLiveData$1.run (RoomTrackingLiveData.java:90)
```

**Comment by Jean-BaptisteC** [comment]
I guess, app crashed because icons is too big (size) and cannot be contain in database
[Exception java.lang.RuntimeException: Exception while computing database live data.](https://stackoverflow.com/questions/73083812/java-lang-runtimeexception-exception-while-computing-database-live-data)

Other crashs with similar problem ?
Input dispatching timed out
org.eu.exodus_privacy.exodusprivacy.utils.PackageManagerModule.provideApplicationList
```
#00  pc 0x000000000004bf9c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  #01  pc 0x000000000047a430  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140)
  #02  pc 0x00000000005cf0d8  /apex/com.android.art/lib64/libart.so (art::JNI<false>::ExceptionOccurred(_JNIEnv*)+908)
  #03  pc 0x000000000049a6c8  /system/lib64/libhwui.so (ImageDecoder_nDecodeBitmap(_JNIEnv*, _jobject*, long, _jobject*, unsigned char, int, int, _jobject*, unsigned char, int, unsigned char, unsigned char, unsigned char, long, unsigned char)+1024)
  at android.graphics.ImageDecoder.nDecodeBitmap (Native method)
  at android.graphics.ImageDecoder.decodeBitmapInternal (ImageDecoder.java:1720)
  at android.graphics.ImageDecoder.decodeDrawableImpl (ImageDecoder.java:1803)
  at android.graphics.ImageDecoder.decodeDrawable (ImageDecoder.java:1759)
  at android.content.res.ResourcesImpl.decodeImageDrawable (ResourcesImpl.java:816)
  at android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:879)
  at android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:681)
  at android.content.res.Resources.loadDrawable (Resources.java:993)
  at android.content.res.TypedArray.getDrawableForDensity (TypedArray.java:1007)
  at android.graphics.drawable.AdaptiveIconDrawable.updateLayerFromTypedArray (AdaptiveIconDrawable.java:530)
  at android.graphics.drawable.AdaptiveIconDrawable.inflateLayers (AdaptiveIconDrawable.java:494)
  at android.graphics.drawable.AdaptiveIconDrawable.inflate (AdaptiveIconDrawable.java:235)
  at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity (DrawableInflater.java:145)
  at android.graphics.drawable.Drawable.createFromXmlInnerForDensity (Drawable.java:1399)
  at android.graphics.drawable.Drawable.createFromXmlForDensity (Drawable.java:1358)
  at android.content.res.ResourcesImpl.loadXmlDrawable (ResourcesImpl.java:919)
  at android.content.res.ResourcesImpl.loadDrawableForCookie (ResourcesImpl.java:873)
  at android.content.res.ResourcesImpl.loadDrawable (ResourcesImpl.java:681)
  at android.content.res.Resources.loadDrawable (Resources.java:993)
  at android.content.res.Resources.getDrawableForDensity (Resources.java:983)
  at android.content.res.Resources.getDrawable (Resources.java:922)
  at android.app.ApplicationPackageManager.getDrawable (ApplicationPackageManager.java:1507)
  at android.app.ApplicationPackageManager.loadUnbadgedItemIcon (ApplicationPackageManager.java:3036)
  at android.app.ApplicationPackageManager.loadItemIcon (ApplicationPackageManager.java:3008)
  at android.content.pm.PackageItemInfo.loadIcon (PackageItemInfo.java:286)
  at org.eu.exodus_privacy.exodusprivacy.utils.PackageManagerModule.provideApplicationList (PackageManagerModule.kt:48)
  at org.eu.exodus_privacy.exodusprivacy.utils.PackageManagerModule_ProvideApplicationListFactory.provideApplicationList (PackageManagerModule_ProvideApplicationListFactory.java:43)
  at org.eu.exodus_privacy.exodusprivacy.DaggerExodusApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get (DaggerExodusApplication_HiltComponents_SingletonC.java:827)
  at dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
  at org.eu.exodus_privacy.exodusprivacy.DaggerExodusApplication_HiltComponents_SingletonC$ServiceCImpl.injectExodusUpdateService2 (DaggerExodusApplication_HiltComponents_SingletonC.java:720)
  at org.eu.exodus_privacy.exodusprivacy.DaggerExodusApplication_HiltComponents_SingletonC$ServiceCImpl.injectExodusUpdateService (DaggerExodusApplication_HiltComponents_SingletonC.java:716)
  at org.eu.exodus_privacy.exodusprivacy.Hilt_ExodusUpdateService.inject (Hilt_ExodusUpdateService.java:53)
  at org.eu.exodus_privacy.exodusprivacy.Hilt_ExodusUpdateService.onCreate (Hilt_ExodusUpdateService.java:30)
  at org.eu.exodus_privacy.exodusprivacy.ExodusUpdateService.onCreate (ExodusUpdateService.kt:80)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4628)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:261)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2173)
  at android.os.Handler.dispatchMessage (Handler.java:111)
  at android.os.Looper.loopOnce (Looper.java:238)
  at android.os.Looper.loop (Looper.java:357)
  at android.app.ActivityThread.main (ActivityThread.java:8089)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1026)
```
