### ISSUE TITLE
Crash - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#334]
```
Exception java.lang.IllegalArgumentException:
  at u0.l.M (SourceFile:201)
  at u0.l.L
  at u0.l.O (SourceFile:15)
  at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.AppsRVAdapter.onBindViewHolder$lambda$3$lambda$0 (SourceFile:43)
  at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.AppsRVAdapter.e
  at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.a.onClick
  at android.view.View.performClick (View.java:6697)
  at android.view.View.performClickInternal (View.java:6674)
  at android.view.View.access$3400 (View.java:798)
  at android.view.View$PerformClick.run (View.java:26263)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:211)
  at android.app.ActivityThread.main (ActivityThread.java:7234)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:503)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:887)
```

https://github.com/Exodus-Privacy/exodus-android-app/blob/78f5d380d42a63ff60b1638e8ea74c84b97af1a7/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps/model/AppsRVAdapter.kt#L43

**Comment by Jean-BaptisteC** [comment]
Similar crashes
```
FATAL EXCEPTION: main
Process: org.eu.exodus_privacy.exodusprivacy.debug, PID: 26946
java.lang.IllegalArgumentException: Navigation action/destination org.eu.exodus_privacy.exodusprivacy.debug:id/action_appDetailFragment_to_trackerDetailFragment cannot be found from the current destination Destination(org.eu.exodus_privacy.exodusprivacy.debug:id/appsFragment) label=fragment_apps class=org.eu.exodus_privacy.exodusprivacy.fragments.apps.AppsFragment
at androidx.navigation.NavController.navigate(NavController.kt:1686)
at androidx.navigation.NavController.navigate(NavController.kt:1604)
at androidx.navigation.NavController.navigate(NavController.kt:2164)
at org.eu.exodus_privacy.exodusprivacy.fragments.trackers.model.TrackersRVAdapter.onBindViewHolder$lambda$4$lambda$3(TrackersRVAdapter.kt:121)
at org.eu.exodus_privacy.exodusprivacy.fragments.trackers.model.TrackersRVAdapter.$r8$lambda$LMQEiMm0lZxFC6q8avJo-ZlQ_bI(Unknown Source:0)
at org.eu.exodus_privacy.exodusprivacy.fragments.trackers.model.TrackersRVAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:8)
at android.view.View.performClick(View.java:7659)
at android.view.View.performClickInternal(View.java:7636)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30156)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
```
FATAL EXCEPTION: main
Process: org.eu.exodus_privacy.exodusprivacy.debug, PID: 28239
java.lang.IllegalArgumentException: Navigation action/destination org.eu.exodus_privacy.exodusprivacy.debug:id/action_trackerDetailFragment_to_appDetailFragment cannot be found from the current destination Destination(org.eu.exodus_privacy.exodusprivacy.debug:id/trackersFragment) label=TrackersFragment class=org.eu.exodus_privacy.exodusprivacy.fragments.trackers.TrackersFragment
at androidx.navigation.NavController.navigate(NavController.kt:1686)
at androidx.navigation.NavController.navigate(NavController.kt:1604)
at androidx.navigation.NavController.navigate(NavController.kt:2164)
at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.AppsRVAdapter.onBindViewHolder$lambda$3$lambda$0(AppsRVAdapter.kt:47)
at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.AppsRVAdapter.$r8$lambda$Aw6tYrv1Xp7aeJ0gpxHRU82kqY8(Unknown Source:0)
at org.eu.exodus_privacy.exodusprivacy.fragments.apps.model.AppsRVAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
at android.view.View.performClick(View.java:7659)
at android.view.View.performClickInternal(View.java:7636)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30156)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
