### ISSUE TITLE
Crash after initial scan

### ISSUE THREAD

**Issue by tdelmas** [Exodus-Privacy/exodus-android-app#57]
The application show the apps, start the loading indicator and crash a few seconds latter.

Android 5.0.1 (Samsung S4)

(It worked before Exodus v1.2.2)

```
E/art: Throwing OutOfMemoryError "Failed to allocate a 24 byte allocation with 6 free bytes and 6B until OOM"
```

And then:

```

I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.586ms total 320.281ms
I/art: WaitForGcToComplete blocked for 331.237ms for cause Alloc
E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 6 free bytes and 6B until OOM" (recursive case)
E/art: "main" prio=5 tid=1 Runnable
      | group="main" sCount=0 dsCount=0 obj=0x77645f48 self=0xb4e07800
      | sysTid=17544 nice=0 cgrp=apps sched=0/0 handle=0xb6fa0ec8
      | state=R schedstat=( 0 0 0 ) utm=637 stm=32 core=1 HZ=100
      | stack=0xbe15c000-0xbe15e000 stackSize=8MB
      | held mutexes= "mutator lock"(shared held)
        at java.lang.Float.valueOf(Float.java:403)
        at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.getAnimatedValue(PropertyValuesHolder.java:1268)
        at android.animation.ValueAnimator.getAnimatedValue(ValueAnimator.java:760)
        at android.support.v4.widget.CircularProgressDrawable$1.onAnimationUpdate(CircularProgressDrawable.java:571)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
        at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:659)
        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
        at android.view.Choreographer.doCallbacks(Choreographer.java:590)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke!(Native method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.556ms total 358.734ms
I/art: WaitForGcToComplete blocked for 671.752ms for cause Alloc
E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 6 free bytes and 6B until OOM" (recursive case)
    "Thread-1041" prio=5 tid=14 Runnable
      | group="main" sCount=0 dsCount=0 obj=0x132090f0 self=0xb4e0ac00
      | sysTid=17619 nice=0 cgrp=apps sched=0/0 handle=0xaf256e80
      | state=R schedstat=( 0 0 0 ) utm=1049 stm=109 core=0 HZ=100
      | stack=0x9b818000-0x9b81a000 stackSize=1036KB
      | held mutexes= "mutator lock"(shared held)
        at java.util.Arrays.copyOfRange(Arrays.java:2701)
        at java.lang.String.<init>(String.java:421)
        at org.json.JSONTokener.nextString(JSONTokener.java:210)
        at org.json.JSONTokener.nextValue(JSONTokener.java:107)
        at org.json.JSONTokener.readObject(JSONTokener.java:362)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONTokener.readArray(JSONTokener.java:430)
        at org.json.JSONTokener.nextValue(JSONTokener.java:103)
        at org.json.JSONTokener.readObject(JSONTokener.java:385)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONObject.<init>(JSONObject.java:156)
        at org.json.JSONObject.<init>(JSONObject.java:173)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.makeDataRequest(NetworkManager.java:165)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.getApplications(NetworkManager.java:221)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.run(NetworkManager.java:125)
I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 9(608B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.495ms total 309.661ms
I/art: WaitForGcToComplete blocked for 636.138ms for cause Alloc
I/art: WaitForGcToComplete blocked for 298.553ms for cause Alloc
D/AndroidRuntime: Shutting down VM
I/Process: Sending signal. PID: 17544 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

```

**Comment by Schoumi** [comment]
i'll look into it tomorrow, thanks for the report

**Comment by tdelmas** [comment]
Thanks. Maybe it's just because I have an old smartphone. I've run the profiler, I see the memory usage increase to ~128(if I remember correctly) in ~2-3seconds and then stays at that value for ~10s then crash.

**Comment by tdelmas** [comment]
I wanted to do a `git bisect` but I realized that the old versions now crash on my phone on startup too. 

Manually built 1.1.1 : 
![image](https://user-images.githubusercontent.com/1955774/62727316-846a0480-ba19-11e9-8d8c-189479f02869.png)

The last visible message before the crash is "Récupération des applications : en attente de connection au server". After a few seconds the waiting animation under that message starts to lag and then the application crash.

Version 1.1.0 and 1.1.1 on F-Droid also crashes.

So it's either a change on my phone (I may have disabled or enabled a Samsung preinstalled crapware?), or on the API server (bigger JSON result, or a different TLS stack?)

**Comment by tdelmas** [comment]
(I didn't succeed to reproduce the crash on emulators, feel free to close this ticket if you can't reproduce it either)
I'm available if you need anymore details.

**Comment by Schoumi** [comment]
The memory size is due to new management of some data and i need to think how to handle it better to avoid too much memory use and still has performance enhancement.

Weird that previous version crash. API hasn't change and stack either as far as i know. i'll try to make a version you could try at the end of the day or tomorrow. Crapware won't interact with the version

**Comment by Schoumi** [comment]
After more investigation it's not the new way to handle data. I experience an unexpected big memory load during the trackers and reports download. It explain why new and old version crash (nothing change in there since a while)
I'm trying to tracking the origin of this amount of data but experience long freeze with profiling tools in android studio.
Fix will arrive later this week i hope.

**Comment by tdelmas** [comment]
Thank you for the update!

**Comment by tdelmas** [comment]
Fixed with https://mamot.fr/web/statuses/102685417977299345

**Comment by Schoumi** [comment]
link ask for login

**Comment by tdelmas** [comment]
It was the apk you sent me from framapiaf.org the 26 aug. :smile: (https://framadrop.org/r/gtKImujlb0#m2hUvCIWlpB1cKUKUnz7hhzlZlZjtX7OX7TemDUQDQA)
