### ISSUE TITLE
Could not allocate CursorWindow

### ISSUE THREAD

**Issue by traumschule** [Exodus-Privacy/exodus-android-app#77]
Version: 2.0.0

Exodus did the initial scan after loading the trackers, now it fails to load the db, this time no memory issue tho (#57).

```
04-12 21:03:52.486  1266  4224 D GameManagerService: identifyGamePackage. org.eu.exodus_privacy.exodusprivacy, mCurrentUserId: 0, callerUserId: 0
04-12 21:03:52.486  1266  4224 D GamePkgDataHelper: getGamePkgData(). org.eu.exodus_privacy.exodusprivacy
04-12 21:03:52.883  1266  1898 E Watchdog: !@Sync 3974 [2020-04-12 21:03:52.883] FD count : 529
04-12 21:03:53.466 27473 27493 W y.exodusprivac: resources.arsc in APK '/data/app/SCRUBBED/base.apk' is compressed.
04-12 21:03:53.840 27473 27493 E CursorWindow: CursorWindow create() failed with -12 errno
04-12 21:03:53.840 27473 27493 E CursorWindow: Could not allocate CursorWindow '/data/user/0/org.eu.exodus_privacy.exodusprivacy/databases/Exodus.db' of size 4194304 due to error -12.
04-12 21:03:53.846 27473 27493 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
04-12 21:03:53.846 27473 27493 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 27473
04-12 21:03:53.846 27473 27493 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 4194304 bytes failed. # Open Cursors=323 (# cursors opened by this proc=323)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.CursorWindow.<init>(CursorWindow.java:136)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:315)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:155)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:149)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.manager.DatabaseManager.getReportFor(DatabaseManager.java:192)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.fragments.ComputeAppListTask.buildViewModelFromPackageInfo(ComputeAppListTask.java:79)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.fragments.ComputeAppListTask.convertPackagesToViewModels(ComputeAppListTask.java:63)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.fragments.ComputeAppListTask.doInBackground(ComputeAppListTask.java:44)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.fragments.ComputeAppListTask.doInBackground(ComputeAppListTask.java:16)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-12 21:03:53.846 27473 27493 E AndroidRuntime: 	... 4 more
04-12 21:03:53.852  1266  2040 D Debug   : !@DumpState : SHIP
04-12 21:03:53.852  1266  2040 D Debug   : !@DumpState : debug level:0x4f4c
04-12 21:03:53.852  1266  2040 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
04-12 21:03:53.852  1266  2040 W ActivityManager: crash : org.eu.exodus_privacy.exodusprivacy,0
04-12 21:03:53.857  1266  2040 W ActivityManager:   Force finishing activity org.eu.exodus_privacy.exodusprivacy/.MainActivity
```

Sounds like a cursor leak in [DatabaseManager.java](/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/DatabaseManager.java#L192).

**Comment by Schoumi** [comment]
Hi, could you try the version [here](https://mob-dev.fr/app-debug.apk) if it still has the problem. I have fix multiple cursor leak in the app. it may have many other problem (it's a work in progress on many things but i hope it help with this problem)
